<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Common.Base</AssemblyName>
    <RootNamespace>Codev.Core.Common.Base</RootNamespace>
    <Version>3.1.1</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.11" />
  </ItemGroup>

</Project>
