<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Provider.Export</AssemblyName>
    <RootNamespace>Codev.Core.Provider.Export</RootNamespace>
    <Version>3.1.1</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.2.2" />
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" Version="1.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Interface.csproj" />
    <ProjectReference Include="..\..\Common\Model\Codev.Core.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="runtimes\linux-x64\native\wkhtmltoimage">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\wkhtmltopdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\help-wkhtmltoimage.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\help-wkhtmltopdf.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\wkhtmltoimage.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\wkhtmltopdf.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /icerky $(ProjectDir)bin\$(Configuration)\net9.0\runtimes\ $(SolutionDir)Publish\bin\Export\$(Configuration)\net9.0\runtimes&#xD;&#xA;rd /s /q $(SolutionDir)\Publish\bin\Export" />
  </Target>

</Project>
