<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Service.Banking</AssemblyName>
    <RootNamespace>Codev.Core.Service.Banking</RootNamespace>
    <Version>3.1.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Banking\Dev</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Banking\Test</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Stage|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Banking\Stage</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Banking\Live</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Interface.csproj" />
    <ProjectReference Include="..\..\Common\Model\Codev.Core.Model.csproj" />
    <ProjectReference Include="..\..\Provider\Banking\Fake\Codev.Core.Provider.Banking.Fake.csproj" />
    <ProjectReference Include="..\..\Provider\Banking\Memory\Codev.Core.Provider.Banking.Memory.csproj" />
    <ProjectReference Include="..\..\Provider\Banking\PayPal\Codev.Core.Provider.Banking.PayPal.csproj" />
    <ProjectReference Include="..\..\Provider\Banking\Stripe\Codev.Core.Provider.Banking.Stripe.csproj" />
    <ProjectReference Include="..\..\Provider\Banking\Stub\Codev.Core.Provider.Banking.Stub.csproj" />
    <ProjectReference Include="..\..\Repository\Ado\Codev.Core.Repository.Ado.csproj" />
    <ProjectReference Include="..\Common\Codev.Core.Service.Common.csproj" />
  </ItemGroup>

</Project>
