<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>

    <Configurations>Dev;Live</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NodaTime" Version="3.2.2" />
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" Version="1.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Interface.csproj" />
    <ProjectReference Include="..\..\Provider\Cipher\Codev.Core.Provider.Cipher.csproj" />
  </ItemGroup>

</Project>
