<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Provider.Common</AssemblyName>
    <RootNamespace>Codev.Core.Provider.Common</RootNamespace>
    <Version>3.1.1</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Interface.csproj" />
    <ProjectReference Include="..\..\Common\Model\Codev.Core.Model.csproj" />
  </ItemGroup>

</Project>
