<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Service.Cache</AssemblyName>
    <RootNamespace>Codev.Core.Service.Cache</RootNamespace>
    <Version>3.1.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Cache\Dev</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Cache\Test</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Stage|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Cache\Stage</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
    <OutputPath>..\..\Publish\bin\Cache\Live</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Common.Interface.csproj" />
    <ProjectReference Include="..\..\Common\Model\Codev.Core.Model.csproj" />
    <ProjectReference Include="..\..\Provider\Cache\Codev.Core.Provider.Cache.csproj" />
    <ProjectReference Include="..\Common\Codev.Core.Service.Common.csproj" />
  </ItemGroup>

</Project>
