<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Repository.Sqlite</AssemblyName>
    <RootNamespace>Codev.Core.Repository.Sqlite</RootNamespace>
    <Version>3.1.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Stage|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />
    <PackageReference Include="NodaTime" Version="3.2.1" />
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" Version="1.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\Common\Interface\Codev.Core.Interface.csproj" />
    <ProjectReference Include="..\..\Common\Model\Codev.Core.Model.csproj" />
  </ItemGroup>

</Project>
