<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Live;Dev</Configurations>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
		<OutputPath>..\Publish\bin\Infrastructure\Dev</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
		<OutputPath>..\Publish\bin\Infrastructure\Live</OutputPath>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repository\Ado\Codev.Core.Repository.Ado.csproj" />
    <ProjectReference Include="..\Service\Asset\Codev.Core.Service.Asset.csproj" />
    <ProjectReference Include="..\Service\Banking\Codev.Core.Service.Banking.csproj" />
    <ProjectReference Include="..\Service\Cache\Codev.Core.Service.Cache.csproj" />
    <ProjectReference Include="..\Service\Cipher\Codev.Core.Service.Cipher.csproj" />
    <ProjectReference Include="..\Service\Common\Codev.Core.Service.Common.csproj" />
    <ProjectReference Include="..\Service\Communication\Codev.Core.Service.Communication.csproj" />
    <ProjectReference Include="..\Service\Export\Codev.Core.Service.Export.csproj" />
    <ProjectReference Include="..\Service\Licensing\Codev.Core.Service.Licensing.csproj" />
    <ProjectReference Include="..\Service\Task\Codev.Core.Service.Task.csproj" />
  </ItemGroup>

</Project>
