<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <AssemblyName>Codev.Core.Provider.Banking.Fake</AssemblyName>
    <RootNamespace>Codev.Core.Provider.Banking.Fake</RootNamespace>
    <Version>3.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Base\Codev.Core.Base.csproj" />
    <ProjectReference Include="..\..\..\Common\Interface\Codev.Core.Common.Interface.csproj" />
    <ProjectReference Include="..\..\..\Common\Model\Codev.Core.Model.csproj" />
  </ItemGroup>

</Project>
